name: firewall-gael
version: "1.0-core22"
base: core22
summary: Firewall script launcher
description: Firewall script launcher

grade: stable
confinement: strict
license: GPL-3.0

architectures:
  - build-on: amd64
    build-for: amd64

apps:
  srv:
    command: bin/srv
    daemon: oneshot
    plugs: [ firewall-control ]
  clear:
    command: bin/clear
    plugs: [ firewall-control ]

parts:
  wrapper:
    plugin: dump
    source: snap/local
