name: firewall-gael
version: "v1.0-core24"
base: core24
summary: Firewall script launcher
description: Firewall script launcher

grade: stable
confinement: strict
license: GPL-3.0

platforms:
  amd64:

apps:
  srv:
    command: bin/srv
    daemon: oneshot
    plugs: [ firewall-control ]
  clear:
    command: bin/clear
    plugs: [ firewall-control ]

parts:
  wrapper:
    plugin: dump
    source: snap/local
